CREATE TABLE "clientMessages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clientMessages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" text NOT NULL,
	"message" text NOT NULL,
	"timestamp" timestamp with time zone DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "clientVersions" (
	"version" text PRIMARY KEY NOT NULL,
	"endOfLife" boolean DEFAULT false NOT NULL,
	"downloadUrl" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "configurationProfiles" (
	"username" text NOT NULL,
	"profile" text NOT NULL,
	"configuration" text NOT NULL,
	CONSTRAINT "configurationProfiles_username_profile_pk" PRIMARY KEY("username","profile")
);
--> statement-breakpoint
CREATE TABLE "fakeMinecraftUsers" (
	"username" text NOT NULL,
	"token" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "featuredServers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "featuredServers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"address" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minecraftUsers" (
	"username" text PRIMARY KEY NOT NULL,
	"firstSeen" timestamp with time zone DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"username" text NOT NULL,
	"token" text PRIMARY KEY NOT NULL,
	"creationDate" timestamp with time zone DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "telemetryActiveModifications" (
	"sessionId" integer NOT NULL,
	"name" text NOT NULL,
	"version" text NOT NULL,
	CONSTRAINT "telemetryActiveModifications_sessionId_name_version_pk" PRIMARY KEY("sessionId","name","version")
);
--> statement-breakpoint
CREATE TABLE "telemetryActiveModules" (
	"sessionId" integer NOT NULL,
	"id" text NOT NULL,
	"enabled" boolean NOT NULL,
	CONSTRAINT "telemetryActiveModules_sessionId_id_pk" PRIMARY KEY("sessionId","id")
);
--> statement-breakpoint
CREATE TABLE "telemetryDiscord" (
	"sessionId" integer PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"username" text NOT NULL,
	"discriminator" text
);
--> statement-breakpoint
CREATE TABLE "telemetryModifications" (
	"name" text NOT NULL,
	"version" text NOT NULL,
	CONSTRAINT "telemetryModifications_name_version_pk" PRIMARY KEY("name","version")
);
--> statement-breakpoint
CREATE TABLE "telemetryModules" (
	"id" text PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "telemetrySessions" (
	"username" text NOT NULL,
	"sessionId" integer PRIMARY KEY NOT NULL,
	"sessionStart" timestamp with time zone DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "telemetrySystem" (
	"sessionId" integer PRIMARY KEY NOT NULL,
	"osName" text NOT NULL,
	"osVersion" text NOT NULL,
	"osArch" text NOT NULL,
	"cpuCores" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"username" text PRIMARY KEY NOT NULL,
	"administrator" boolean DEFAULT false NOT NULL,
	"passwordHash" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "clientMessages" ADD CONSTRAINT "clientMessages_username_minecraftUsers_username_fk" FOREIGN KEY ("username") REFERENCES "public"."minecraftUsers"("username") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "configurationProfiles" ADD CONSTRAINT "configurationProfiles_username_minecraftUsers_username_fk" FOREIGN KEY ("username") REFERENCES "public"."minecraftUsers"("username") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "fakeMinecraftUsers" ADD CONSTRAINT "fakeMinecraftUsers_username_minecraftUsers_username_fk" FOREIGN KEY ("username") REFERENCES "public"."minecraftUsers"("username") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_username_users_username_fk" FOREIGN KEY ("username") REFERENCES "public"."users"("username") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "telemetryActiveModifications" ADD CONSTRAINT "telemetryActiveModifications_sessionId_telemetrySessions_sessionId_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."telemetrySessions"("sessionId") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "telemetryActiveModifications" ADD CONSTRAINT "telemetryActiveModifications_name_version_telemetryModifications_name_version_fk" FOREIGN KEY ("name","version") REFERENCES "public"."telemetryModifications"("name","version") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "telemetryActiveModules" ADD CONSTRAINT "telemetryActiveModules_sessionId_telemetrySessions_sessionId_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."telemetrySessions"("sessionId") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "telemetryActiveModules" ADD CONSTRAINT "telemetryActiveModules_id_telemetryModules_id_fk" FOREIGN KEY ("id") REFERENCES "public"."telemetryModules"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "telemetryDiscord" ADD CONSTRAINT "telemetryDiscord_sessionId_telemetrySessions_sessionId_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."telemetrySessions"("sessionId") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "telemetrySessions" ADD CONSTRAINT "telemetrySessions_username_minecraftUsers_username_fk" FOREIGN KEY ("username") REFERENCES "public"."minecraftUsers"("username") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "telemetrySystem" ADD CONSTRAINT "telemetrySystem_sessionId_telemetrySessions_sessionId_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."telemetrySessions"("sessionId") ON DELETE cascade ON UPDATE cascade;